//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhavani_Globall
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankMaster
    {
        public int BankId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<long> BankAccountNo { get; set; }
        public string EmployeeName { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string AccountType { get; set; }
        public string IFSCCode { get; set; }
        public string MICRNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
