//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhavani_Globall
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public int CustomerId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string ShipmentMethod { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
