//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhavani_Globall
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceMaster
    {
        public int InvoiceId { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> TransportId { get; set; }
        public Nullable<int> PayModeId { get; set; }
        public Nullable<int> shipmentId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TransportCost { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> PendingAmount { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> Createby { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
