//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhavani_Globall
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public int ProductId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubcategoryId { get; set; }
        public Nullable<int> TransportId { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDetails { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<decimal> ProductQuantity { get; set; }
        public string ProductImages { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
