//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhavani_Globall
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelaryMaster
    {
        public int SalaryId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> HouseRent { get; set; }
        public Nullable<decimal> TransportAllowance { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> Tex { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
