//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhavani_Globall
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubcategoryMaster
    {
        public int SubcategoryId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string SubcategoryName { get; set; }
        public string SubCategoryDetails { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
